# Generated by Django 4.2.7 on 2023-11-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('virtual_account', models.CharField(max_length=100, unique=True)),
                ('balance', models.IntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('balance_before', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
