# Generated by Django 4.2.7 on 2023-11-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_ledger_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
