# Generated by Django 4.2.7 on 2023-11-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_transaction_account_name_transaction_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_histories', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
