# Generated by Django 4.2.7 on 2023-11-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0004_ledgerstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='external_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
