# Generated by Django 4.2.7 on 2023-11-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_ledger_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ledgerstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
